ENT-6375/master: Removed unnecessary packages promise on SuSE
cfengine/masterfiles pull request #1846
Opened 2020-10-12 16:58 UTC by nickanderson

This packages promise was in place to provide package inventory used by
packagematching() and packageupdatesmatching() out of the box. This is not
needed since ENT-5480 introduced the zypper package module.

Ticket: ENT-6375
Changelog: Title

2020-10-13 14:58 UTC, cf-bottom commented
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

2020-10-13 16:11 UTC, olehermanse requested changes
LGTM, please squash the squashme commits.

2020-10-13 17:02 UTC, olehermanse approved these changes

2020-10-13 17:02 UTC, nickanderson commented
@cf-bottom jenkins, please.

2020-10-13 17:03 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5777)](https://ci.cfengine.com//job/pr-pipeline/5777/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5777/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5777/

2020-10-14 13:27 UTC, nickanderson commented
Failure in jenkins from unrelated tests. One that is known to have stability issues. Merging anyway.
```
Test Result (1 failure / +1)

    ./00_basics/ifelapsed_and_expireafter/timed/defaults.cf.defaults.cf
```

2020-10-14 13:27 UTC, merged