CFE-3556 Add support for openrc services promises
cfengine/masterfiles pull request #2015
Opened 2021-07-09 21:53 UTC by craigcomstock

enabled/disabled state will add/del using rc-update to the default runlevel
as well as start/stop the service immediately

Ticket: CFE-3556
Changelog: title

2021-07-09 21:54 UTC, craigcomstock commented
I made this a WIP because I haven't tested quite enough. Will do.

2021-08-20 14:06 UTC, nickanderson requested changes
Pretty good, just a few things that I think would benefit from change.

- Scope down `rc-update` path to the subsets of linux where it's expected.
- Docstrings for the new `openrc_services` agent bundle
- `service_method` for new `openrc_services` bundle

2021-08-20 14:06 UTC, nickanderson commented on lib/services.cf
> +bundle agent openrc_services(service, state)
Oh, this one is missing docstrings. See bundle agent systemd_services for an example.

2021-08-20 14:06 UTC, nickanderson commented on lib/services.cf
> +bundle agent openrc_services(service, state)
Also, if you want to be able to use this directly like this:

```
services:
  "my-openrc-service"
    service_policy => "my-service-state",
    service_method => openrc_services;
```

Then you will also need a `service_method` body See `body service_method systemd_services` as an example.

2021-12-29 05:09 UTC, bogen85 commented
@craigcomstock Why just the default run level? Why not configurable for any run level?

2022-07-27 20:19 UTC, craigcomstock commented
stale

2022-07-27 20:19 UTC, closed without merging