ENT-7465: Insured exported reports from Mission Portal are in the correct location
cfengine/masterfiles pull request #2064
Opened 2021-08-17 16:11 UTC by nickanderson

Ticket: ENT-7465
Changelog: Title

2021-08-18 09:22 UTC, aleksandrychev requested changes

2021-08-18 09:22 UTC, aleksandrychev commented on cfe_internal/enterprise/CFE_hub_specific.cf
> +      "$(cfe_internal_hub_vars.public_docroot)/tmp/." -> { "ENT-7465" }
in 3.18 (htdocs/public/tmp) and 3.15 (htdocs/tmp) tmp has different location, I'd say to add variable and use it as bundle:
 ```
 vars:
    "tmp_directories_list" slist => {"$(cfe_internal_hub_vars.public_docroot)/tmp/.", "$(cfe_internal_hub_vars.docroot)/tmp/."};
```

2021-08-18 09:22 UTC, aleksandrychev commented on cfe_internal/enterprise/CFE_hub_specific.cf
> +        transformer => "/bin/mv $(this.promiser) $(cfe_internal_hub_vars.public_docroot)/static/",
`$(cfe_internal_hub_vars.public_docroot)/static/`
should be 
`$(cfe_internal_hub_vars.docroot)/static/`

2021-08-18 09:22 UTC, aleksandrychev commented on cfe_internal/enterprise/CFE_hub_specific.cf
> +        if => isdir( "$(cfe_internal_hub_vars.public_docroot)/static/." ),
`$(cfe_internal_hub_vars.public_docroot)/static/`
should be 
`$(cfe_internal_hub_vars.docroot)/static/`

2021-08-19 13:44 UTC, nickanderson commented
Superseded by https://github.com/cfengine/masterfiles/pull/2067

2021-08-19 13:44 UTC, closed without merging