ENT-7359 Removed build dir from install/dist targets
cfengine/masterfiles pull request #2121
Opened 2021-10-20 21:10 UTC by craigcomstock

Instead of creating files from .mustache templates
just copy them over in the tests where they are needed:

tests/unit/test_package_module_apt_get
tests/unit/test_package_module_yum

Ticket: ENT-7359
Changelog: title

2021-10-20 21:11 UTC, craigcomstock commented
@cf-bottom jenkins build please

2021-10-21 15:00 UTC, vpodzime reviewed
What if you just rename `all-local` to `check-local`?

2021-10-21 20:32 UTC, craigcomstock commented
@cf-bottom jenkins

2021-10-21 20:33 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7209)](https://ci.cfengine.com//job/pr-pipeline/7209/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7209/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7209/

2021-10-22 04:34 UTC, vpodzime commented on tests/unit/test_package_module_apt_get
> +os.system("mkdir -p ../../build/modules/packages")
Good point! Let's do `if not os.path.isdir("..."): os.makedirs("...")`

2021-10-22 04:40 UTC, vpodzime commented
> Wouldn't the `build` stuff still be included since it is a top-level target and so included in install/dist?

I don't understand why `build` is not in `SUBDIRS` with the files that should be distributed but not installed in `dist_noinst_DATA`.

2021-11-03 15:48 UTC, craigcomstock commented
@cf-bottom jenkins please, thanks.

2021-11-03 15:49 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7254)](https://ci.cfengine.com//job/pr-pipeline/7254/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7254/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7254/

2021-11-03 20:22 UTC, craigcomstock commented
small adjustment and things are starting to look green! [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=7255)](https://ci.cfengine.com/job/pr-pipeline/7255/)

2021-11-03 21:11 UTC, craigcomstock commented
@cf-bottom jenkins one more time maybe

2021-11-03 21:18 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7256)](https://ci.cfengine.com//job/pr-pipeline/7256/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7256/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7256/

2021-11-04 14:08 UTC, craigcomstock commented on tests/acceptance/17_packages/12_new/timed/packagesmatching.cf
> +      "$(sys.workdir)/modules/packages/."
this is probably not needed now that I am including modules in testall `--includes`

2021-11-04 14:09 UTC, craigcomstock commented
@cf-bottom jenkins please

2021-11-04 14:14 UTC, cf-bottom requested changes
Please use a company e-mail instead of c***@unreasonablefarm.org

2021-11-04 14:14 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=7260)](https://ci.cfengine.com//job/pr-pipeline/7260/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7260/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7260/

2021-11-05 10:07 UTC, vpodzime approved these changes
Looks good to me. Thanks for your persistence and endurance in this!

2021-11-05 13:27 UTC, merged

2021-11-05 15:53 UTC, craigcomstock commented
https://github.com/cfengine/masterfiles/pull/2136 (3.15 cherry pick)
https://github.com/cfengine/masterfiles/pull/2135 (3.18 cherry pick)