Add a test that custom promises are only evaluated once in an agent run
cfengine/masterfiles pull request #2223
Opened 2022-01-19 10:28 UTC by vpodzime

I.e. that elementary promise locking works, as implemented in
cfengine/core@24e2de71c749.

Ticket: CFE-3434
Changelog: None

2022-01-19 10:29 UTC, vpodzime commented
A new test for changes done in https://github.com/cfengine/core/pull/4905.

2022-01-19 12:25 UTC, vpodzime commented
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=7482)](https://ci.cfengine.com/job/pr-pipeline/7482/)

2022-01-21 14:55 UTC, larsewi requested changes

2022-01-21 14:55 UTC, larsewi commented on tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
> +      string => "Test that depends_on works with custom promise types";
Copy pasta
```suggestion
    "description" -> { "CFE-3434" }
      string => "Test that custom promises are only evaluated once";
```

2022-01-21 14:55 UTC, larsewi commented on tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
> +}
No need to include _default.cf.sub_
```suggestion
body common control
{
    bundlesequence => { "init", "test", "check" };
}
```

2022-01-21 14:55 UTC, larsewi commented on tests/acceptance/30_custom_promise_types/append_promises.py
> +        always = attributes.get("always", "false") == "true"
Clever :beers:

2022-01-21 14:58 UTC, larsewi commented
Did you test that this failed before? I guess the init bundle could also be evaluated multiple times.

2022-01-24 14:41 UTC, vpodzime commented on tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
> +      string => "Test that depends_on works with custom promise types";
Good catch!

2022-01-24 14:43 UTC, vpodzime commented
> Did you test that this failed before? I guess the init bundle could also be evaluated multiple times.
Yes, it fails when I run the test with the *master* or *3.18.x* agent.

2022-01-24 14:47 UTC, vpodzime commented
Hmm, `default.cf.sub` is actually needed for `local_cp`.

2022-01-26 17:54 UTC, olehermanse approved these changes
👍

2022-01-26 18:04 UTC, merged