Changelog for 3.18.x
cfengine/masterfiles pull request #2400
Opened 2022-06-14 14:29 UTC by Lex-2008

2022-06-15 12:33 UTC, cf-bottom commented
Thank you for submitting a PR! Maybe @nickanderson can review this?

2022-06-15 20:43 UTC, nickanderson requested changes
I amended the PR title with ticket and specific version this chanelog is targeting.

One suggested change made.

2022-06-15 20:43 UTC, nickanderson commented on CHANGELOG.md
> +	  webdav (ENT-8495)
```suggestion
	  mod_dav (ENT-8495)
```

2022-06-21 13:01 UTC, olehermanse approved these changes

2022-06-21 13:01 UTC, merged