ENT-5866: Fixed set_line_based() for case when edit_defaults.empty_before_use is true
cfengine/masterfiles pull request #2430
Opened 2022-07-15 19:06 UTC by nickanderson

Merge together:

* https://github.com/cfengine/core/pull/4993

The implementation now avoids looking in the original file when the files
promise is instructed to start with an empty file.

The minimum_version and else macros were introduced in 3.15.1 so special care is
taken to cover 3.15.0.

2022-07-15 19:06 UTC, nickanderson commented
@cf-bottom jenkins, please

2022-07-15 19:09 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=8311)](https://ci.cfengine.com//job/pr-pipeline/8311/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8311/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8311/

2022-07-15 20:17 UTC, nickanderson commented
Oh, it's failing travis I think because it's using a package from nightly, not with the changes from core.

2022-07-15 20:17 UTC, nickanderson commented
@cf-bottom jenkins, again please.

2022-07-15 20:18 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=8312)](https://ci.cfengine.com//job/pr-pipeline/8312/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8312/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8312/

2022-07-18 08:12 UTC, vpodzime reviewed
Looks promising to me. But aren't the macros not supported in 3.15.0 an issue because the policy won't even be syntactically correct there?

2022-07-18 13:57 UTC, olehermanse requested changes
Please squash commits and test it, both with new versions and compatibility with 3.15.

2022-07-18 14:41 UTC, craigcomstock commented
@cf-bottom build please

2022-07-18 14:44 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=8314)](https://ci.cfengine.com//job/pr-pipeline/8314/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8314/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8314/

2022-07-18 15:04 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=8315)](https://ci.cfengine.com//job/pr-pipeline/8315/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8315/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8315/

2022-07-18 15:08 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=8316)](https://ci.cfengine.com//job/pr-pipeline/8316/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8316/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8316/

2022-07-18 15:15 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=build-and-deploy-docs-master&build=30)](https://ci.cfengine.com//job/build-and-deploy-docs-master/30/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/30/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-30/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-30/output/_site/

2022-07-18 15:22 UTC, craigcomstock reviewed
looks good, trying a build now.

2022-07-18 17:29 UTC, nickanderson commented
> Please squash commits and test it, both with new versions and compatibility with 3.15.

-   [X] Commits squashed
-   Test results
    -   Behavior on master (3.21.0)
        -   `set_line_based` does properly deals with the combination of `edit_defaults => empty` with a pre-existing file.
    -   Behavior on 3.15.0
        -   Policy works as it did prior to change.
            -   `set_line_based` does **not** work correctly when paired with `edit_defaults => empty`
                -   3.15.0 doesn't have any way to know that `edit_defaults => empty` is in use, thus no way to tweak the implementation to make it smart about differing the behavior.
                -   Prior version of fix resulted in syntax errors for the use of the `before_version` macro which did not exist in 3.15.0, removed it's use and adjusted class guard to handle backwards compatibility.

2022-07-18 18:49 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=build-and-deploy-docs-master&build=31)](https://ci.cfengine.com//job/build-and-deploy-docs-master/31/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/31/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-31/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-31/output/_site/

2022-07-19 12:39 UTC, vpodzime reviewed
We already have an acceptance test for this added in https://github.com/cfengine/core/commit/a8453b1517ffa9be5f72f54d0fd8d988ddd65310 But I'd actually remove that one because `set_line_based()` tests don't really belong to the *core* repo. Looks good to me otherwise.

2022-07-19 12:39 UTC, vpodzime commented on lib/files.cf
> +    (cfengine_3_15|cfengine_3_16|cfengine_3_17|cfengine_3_18|cfengine_19|cfengine_3_20)::
`cfengine_3_19`

2022-07-19 13:45 UTC, nickanderson commented on lib/files.cf
> +    (cfengine_3_15|cfengine_3_16|cfengine_3_17|cfengine_3_18|cfengine_19|cfengine_3_20)::
doh!

2022-07-19 13:58 UTC, craigcomstock approved these changes

2022-07-19 14:12 UTC, nickanderson commented
> We already have an acceptance test for this added in [cfengine/core@a8453b1](https://github.com/cfengine/core/commit/a8453b1517ffa9be5f72f54d0fd8d988ddd65310) But I'd actually remove that one because `set_line_based()` tests don't really belong to the _core_ repo. Looks good to me otherwise.

OK, we can do that on your PR in core. lms if i can push to that branch.

2022-07-19 14:25 UTC, nickanderson commented
> > We already have an acceptance test for this added in [cfengine/core@a8453b1](https://github.com/cfengine/core/commit/a8453b1517ffa9be5f72f54d0fd8d988ddd65310) But I'd actually remove that one because `set_line_based()` tests don't really belong to the _core_ repo. Looks good to me otherwise.
> 
> OK, we can do that on your PR in core. lms if i can push to that branch.

I pulled it in your core PR: https://github.com/cfengine/core/pull/4993/commits/ebe7fefe0a2d6233bbd3aafd7ec4565461e097eb

2022-07-20 08:09 UTC, vpodzime approved these changes
ACK

2022-07-20 10:36 UTC, merged