Changelog for 3.21.0
cfengine/masterfiles pull request #2552
Opened 2022-12-13 17:14 UTC by Lex-2008

2022-12-13 19:54 UTC, nickanderson commented on CHANGELOG.md
> +	- Updated filename conventions for AIX and Solaris packages (ENT-9095)
Merged ENT-9603 after changelog generated. Adding entry:

```suggestion
	- Updated filename conventions for AIX and Solaris packages (ENT-9095)
	- Fixed detection of location for httpd.pid (ENT-9603)
```

2022-12-13 20:02 UTC, nickanderson requested changes
Made some suggestions.

2022-12-13 20:02 UTC, nickanderson commented on CHANGELOG.md
> +	- Make device-tree inventory quieter in containers (#2468) (ENT-9063)
Redacted github PR number.
```suggestion
	- Make device-tree inventory quieter in containers (ENT-9063)
```

2022-12-14 10:52 UTC, olehermanse commented on CHANGELOG.md
> +	- Add inventory for Raspberry Pi and DeviceTree devices (ENT-8628)
```suggestion
	- Added inventory for Raspberry Pi and DeviceTree devices (ENT-8628)
```

2022-12-14 10:52 UTC, olehermanse commented on CHANGELOG.md
> +	- Fix deleting multiple hosts with distributed cleanup utility
```suggestion
	- Fixed deleting multiple hosts with distributed cleanup utility
```

2022-12-14 10:53 UTC, olehermanse commented on CHANGELOG.md
> +	- Improve distributed_cleanup script for testing (ENT-8611)
```suggestion
```

2022-12-14 10:53 UTC, olehermanse commented on CHANGELOG.md
> +	  (ENT-8915)
```suggestion
```

2022-12-14 22:58 UTC, nickanderson commented on CHANGELOG.md
> +	- Added check to make sure cf-execd is running after attempting self upgrade on Windows
Manual changelog entry for https://github.com/cfengine/masterfiles/pull/2554
```suggestion
        - Added policy to enforce proper permissions on Mission Portal ldap directory (ENT-9693)
	- Added check to make sure cf-execd is running after attempting self upgrade on Windows
```

2022-12-15 16:11 UTC, craigcomstock commented on CHANGELOG.md
> +	- Added check to make sure cf-execd is running after attempting self upgrade on Windows
Bad title for https://github.com/cfengine/masterfiles/pull/2555, so here's a better changelog entry:

```suggestion
	- Added check to make sure cf-execd is running after attempting self upgrade on Windows
	- Added exception for settings.ldap.php file for ldap directory permissions (ENT-9697)
```

2022-12-15 16:11 UTC, craigcomstock commented on CHANGELOG.md
> +	- Added check to make sure cf-execd is running after attempting self upgrade on Windows
@nickanderson ^^^

2022-12-15 18:22 UTC, olehermanse approved these changes

2022-12-15 18:23 UTC, merged