ENT-10210: Made mailsubject, mailfilter_include, and mailfilter_exclude configurable via augments
cfengine/masterfiles pull request #2618
Opened 2023-05-10 22:19 UTC by nickanderson

2023-05-11 14:28 UTC, oldgiova approved these changes
LGTM

2023-05-11 15:46 UTC, craigcomstock requested changes

2023-05-11 15:46 UTC, craigcomstock commented on MPF.md
> +When enabled `cf-execd` emails output that differs from previous executions. The subject of the email can be configured by setting `mailsubject` in `body executor control`. The will use the value of
s/The will use/This will use/

2023-05-11 16:51 UTC, nickanderson commented on MPF.md
> +When enabled `cf-execd` emails output that differs from previous executions. The subject of the email can be configured by setting `mailsubject` in `body executor control`. The will use the value of
ACK

2023-05-12 14:42 UTC, craigcomstock approved these changes

2023-05-12 16:46 UTC, merged