ENT-4400: Allowed blob image-src in the Mission Portal CSP rules
cfengine/masterfiles pull request #2949
Opened 2024-10-09 12:30 UTC by aleksandrychev

Highchart export requires it

2024-10-10 14:45 UTC, craigcomstock approved these changes

2024-10-10 14:45 UTC, craigcomstock requested changes
Won't this require the same change in buildscripts repo?

2024-10-11 07:27 UTC, aleksandrychev commented
> Won't this require the same change in buildscripts repo?

@craigcomstock I don't see any of CSP rules there https://github.com/cfengine/buildscripts/blob/master/deps-packaging/apache/httpd.conf

2024-10-11 09:13 UTC, aleksandrychev commented
> Won't this require the same change in buildscripts repo?

added whole rules set https://github.com/cfengine/buildscripts/pull/1504

2024-10-11 15:43 UTC, craigcomstock approved these changes

2024-10-11 15:44 UTC, merged